### ISSUE TITLE
Add LEFT/RIGHT JOINS 

### ISSUE THREAD

**Issue by stefanosusini** [dresende/node-sql-query#22]
Just like this:
common.Select().from('table1')
              .from('table2', 'id2', 'table1', 'id1', 'LEFT').fun('AVG', 'col').build();

"SELECT AVG(`t2`.`col`) FROM `table1` `t1` 
LEFT JOIN `table2` `t2` ON `t2`.`id2` = `t1`.`id1`"

thanks

**Comment by dxg** [comment]
This has been implemented and published in version `0.1.25`
