### ISSUE TITLE
yet another node sql builder?

### ISSUE THREAD

**Issue by tjwebb** [dresende/node-sql-query#40]
Let's join forces guys!

I'd love some help on any/all of these projects:
- https://github.com/balderdashy/waterline-sequel (used by https://github.com/balderdashy/sails)
- https://github.com/tgriesser/knex
- https://github.com/brianc/node-sql

**Comment by dxg** [comment]
Indeed. This sql builder does need some work with respect to building delete queries with joins.
Perhaps if another builder is more mature it may be easier to switch than develop an indigenous solution.
Unfortunately, I don't have time to look into this at the moment.
