### ISSUE TITLE
Is the OR statement missing?

### ISSUE THREAD

**Issue by vfioox** [dresende/node-sql-query#49]
I thought it was missing in the documentation, but isn't the OR statement missing?

So you can build a query like this
`WHERE (col_1 !=1 AND col_2 !=12)
OR (col_1  !=1 AND col_2  !=13)`

Or even just
`WHERE (col_1 !=1) OR (col_2  !=13)`

**Comment by dresende** [comment]
Sorry for not having a proper documentation, look at the tests for good examples. Take a look at this one:

https://github.com/dresende/node-sql-query/blob/master/test/integration/test-where-advanced.js

**Comment by dresende** [comment]
More specifically, your first example:

```js
const q     = require("sql-query");
const Q     = q.query;
const query = new Q;

query.select().where({ or: [{ col_1 : q.ne(1), col_2 : q.ne(12) }, { col_1 : q.ne(1), col_2: q.ne(13) }] })
```

I'm not quite sure about the syntax since I haven't used it for a while but you can check it ;)
