### ISSUE TITLE
insert on duplicate key update

### ISSUE THREAD

**Issue by alator21** [dresende/node-sql-query#60]
This syntax is not supported. https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html

**Comment by dxg** [comment]
Pull requests welcome.

**Comment by alator21** [comment]
@dxg Why did you close the issue? Do we want this syntax or not?

**Comment by dxg** [comment]
@alator21 because the only way to add a feature to a barely maintained repository is by submitting a pull request.

We do not have any active maintainers willing to implement feature requests.
