### ISSUE TITLE
SQL_CALC_FOUND_ROWS

### ISSUE THREAD

**Issue by noazark** [dresende/node-sql-query#7]
It would be nice to add `SQL_CALC_FOUND_ROWS` to select queries in order to subsequently call `SELECT FOUND_ROWS()`. I use this for pagination and it would be really nice to add to the mix! What do you think?

**Comment by lois-dowell** [comment]
$RowSet=$db->GetRowSet($Sql);

	$PageLinks= $pager->GetLinks();
